#Eureka
eureka:
  instance:
    hostname: localhost
    port: 8762
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

#Zipkin
  spring:
    zipkin:
      base-url: http://localhost:9411/
      sender:
        type: web

#sleuth
spring:
  sleuth:
    sampler:
      probability: 1

#Oauth2 Security
security:
  basic:
  #    enabled: false
  oauth2:
    resource:
      #      service-id: ${PREFIX:}resource
      token-info-uri: http://localhost:8765/oauth/check_token
    client:
      client-id: web
      client-secret: test
