server:
  port: 8870

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:~/product-server-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled:  true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#spring.profiles.active=TEST_PROFILE

myapp:
  publickey:
    name: oauthpublickey.cer

########################
# Feign configs
########################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
###
#hystrix

management:
  endpoints:
    web:
      exposure:
        include:
          hystrix: stream