server:
  port: 9191
  
myapp:
  keystore:
    name: keystore.jks
    pass: password
  key:
    name: oauth
    pass: password

spring:
  datasource:
    url: jdbc:h2:~/auth-server-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE








 